{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.betterlang",
    "module": "compiler-plugin",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-plugin-0.1.2.jar",
          "url": "compiler-plugin-0.1.2.jar",
          "size": 22831,
          "sha512": "8db02677b0703902d5a585b6cab5063096b90dd352af1fa61be7de59d4250be64c12be4cba2f5669e05d7bedc36386453fa92951173cd0355650d13547e2e5a5",
          "sha256": "d319d00d99bd755da1eb371a54638e9bc6895f6c1c3afd6c267a7b25af97e021",
          "sha1": "f81e40d5c3de62d913c22a8d4672773d88af8923",
          "md5": "493b4b27d6d6b427d007d32e88666a06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-plugin-0.1.2.jar",
          "url": "compiler-plugin-0.1.2.jar",
          "size": 22831,
          "sha512": "8db02677b0703902d5a585b6cab5063096b90dd352af1fa61be7de59d4250be64c12be4cba2f5669e05d7bedc36386453fa92951173cd0355650d13547e2e5a5",
          "sha256": "d319d00d99bd755da1eb371a54638e9bc6895f6c1c3afd6c267a7b25af97e021",
          "sha1": "f81e40d5c3de62d913c22a8d4672773d88af8923",
          "md5": "493b4b27d6d6b427d007d32e88666a06"
        }
      ]
    }
  ]
}
